"use client";

import * as React from "react";
import * as echarts from "echarts";
import { money } from "@/lib/format";

/**
 * Brand-derived categorical palette: anchored on the brand red (#AF3931 ≈ H4°, S.72, V.686) and
 * generated by rotating ONLY the hue in even steps. Every swatch shares the brand red's saturation
 * and value, so the set stays tonally on-brand while each series/slice gets a distinct hue (no
 * confusing near-duplicate reds). Color 0 is the brand red.
 */
function hsvToHex(h: number, s: number, v: number): string {
  const c = v * s;
  const x = c * (1 - Math.abs(((h / 60) % 2) - 1));
  const m = v - c;
  const [r, g, b] = (
    h < 60 ? [c, x, 0] : h < 120 ? [x, c, 0] : h < 180 ? [0, c, x] :
    h < 240 ? [0, x, c] : h < 300 ? [x, 0, c] : [c, 0, x]
  );
  const hx = (n: number) => Math.round((n + m) * 255).toString(16).padStart(2, "0");
  return `#${hx(r)}${hx(g)}${hx(b)}`;
}

function brandPalette(n: number, hue0 = 4, s = 0.72, v = 0.686): string[] {
  return Array.from({ length: n }, (_, i) => hsvToHex((hue0 + (i * 360) / n) % 360, s, v));
}

export const CHART_COLORS = brandPalette(8);

function themeColors() {
  const cs = getComputedStyle(document.documentElement);
  const pick = (v: string, f: string) => (cs.getPropertyValue(v).trim() || f);
  return { label: pick("--color-secondary", "#615D5C"), line: pick("--color-subtle", "#e6e2e1") };
}

/** Inject palette + light/dark axis/text colors into any option (axes may be object or array). */
function withTheme(option: any) {
  const { label, line } = themeColors();
  const themeAxis = (ax: any) => ({
    axisLabel: { color: label, ...(ax?.axisLabel ?? {}) },
    axisLine: { lineStyle: { color: line }, ...(ax?.axisLine ?? {}) },
    splitLine: { lineStyle: { color: line }, ...(ax?.splitLine ?? {}) },
    ...ax,
  });
  const themeAxes = (a: any) => (a == null ? a : Array.isArray(a) ? a.map(themeAxis) : themeAxis(a));
  return {
    color: CHART_COLORS,
    textStyle: { color: label, fontFamily: "inherit" },
    ...option,
    xAxis: themeAxes(option.xAxis),
    yAxis: themeAxes(option.yAxis),
  };
}

/** ECharts wrapped for React: init on a ref, resize with the container, re-theme on light/dark toggle. */
export function EChart({ option, height = 280 }: { option: any; height?: number }) {
  const ref = React.useRef<HTMLDivElement>(null);
  const chart = React.useRef<echarts.ECharts | null>(null);
  const optionRef = React.useRef(option);
  optionRef.current = option;

  const apply = React.useCallback(() => {
    chart.current?.setOption(withTheme(optionRef.current), true);
  }, []);

  React.useEffect(() => {
    const el = ref.current;
    if (!el) return;
    const c = echarts.init(el, null, { renderer: "svg" });
    chart.current = c;
    const ro = new ResizeObserver(() => c.resize());
    ro.observe(el);
    const mo = new MutationObserver(apply);
    mo.observe(document.documentElement, { attributes: true, attributeFilter: ["class"] });
    apply();
    return () => { ro.disconnect(); mo.disconnect(); c.dispose(); chart.current = null; };
  }, [apply]);

  React.useEffect(() => { apply(); }, [option, apply]);

  return <div ref={ref} style={{ width: "100%", height }} />;
}

/* ----------------------------- Option builders ----------------------------- */

const compact = (v: number) => {
  const a = Math.abs(v);
  if (a >= 1e9) return `${(v / 1e9).toFixed(1)}B`;
  if (a >= 1e6) return `${(v / 1e6).toFixed(1)}M`;
  if (a >= 1e3) return `${(v / 1e3).toFixed(0)}K`;
  return String(v);
};

const baseGrid = { left: 8, right: 16, top: 24, bottom: 8, containLabel: true };

export function barOption({ categories, values, money: isMoney }: { categories: string[]; values: number[]; money?: boolean }) {
  return {
    grid: baseGrid,
    tooltip: { trigger: "axis", valueFormatter: (v: any) => (isMoney ? money(Number(v)) : String(v)) },
    xAxis: { type: "category", data: categories, axisLabel: { interval: 0, rotate: categories.length > 4 ? 28 : 0 } },
    yAxis: { type: "value", axisLabel: { formatter: (v: number) => (isMoney ? compact(v) : String(v)) } },
    series: [{ type: "bar", data: values, barMaxWidth: 44, itemStyle: { borderRadius: [4, 4, 0, 0] } }],
  };
}

export function stackedBarOption({ categories, series, money: isMoney }: {
  categories: string[]; series: { name: string; values: number[] }[]; money?: boolean;
}) {
  return {
    grid: { ...baseGrid, top: 34 },
    legend: { top: 0 },
    tooltip: { trigger: "axis", valueFormatter: (v: any) => (isMoney ? money(Number(v)) : String(v)) },
    xAxis: { type: "category", data: categories, axisLabel: { interval: 0, rotate: categories.length > 4 ? 28 : 0 } },
    yAxis: { type: "value", axisLabel: { formatter: (v: number) => (isMoney ? compact(v) : String(v)) } },
    series: series.map((s) => ({ name: s.name, type: "bar", stack: "total", data: s.values, barMaxWidth: 44 })),
  };
}

export function donutOption({ items }: { items: { name: string; value: number }[] }) {
  return {
    tooltip: { trigger: "item" },
    legend: { bottom: 0, type: "scroll" },
    series: [{
      type: "pie", radius: ["46%", "70%"], center: ["50%", "44%"],
      data: items, label: { show: false }, itemStyle: { borderColor: "var(--color-card)", borderWidth: 2 },
    }],
  };
}
